site_name: "Copier PDM"
site_description: "A Copier template for PDM projects"
site_url: "https://copier-pdm.fming.dev"
repo_url: "https://github.com/pdm-project/copier-pdm"
repo_name: "pdm-project/copier-pdm"
site_dir: "site"

nav:
  - Home:
      - Overview: index.md
      - Changelog: changelog.md
  - Development:
      - Contributing: contributing.md
      - Code of Conduct: code_of_conduct.md

theme:
  name: material
  palette:
    primary: deep purple
    accent: teal
  font:
    text: Open Sans
    code: Fira Code
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "#"

plugins:
  - search
